---
#
# Include the shared gitlab CI definitions
#
include:
  - project: 'enterprisemodules/gitlab_ci'
    file: 'gitlab-ci.yml'

setup RCU:
  stage: acceptance setup
  tags:
    - demo_check
  before_script:
    - mkdir -p modules/software/files
    - cp ~/software/linuxx64_12201_database.zip modules/software/files
  script:
  - vagrant up ml-rcudb
  only:
    refs:
      - master

forms_12213_demo_check:
  extends: .demo_check
  before_script:
    - mkdir -p modules/software/files
    - cp ~/software/jdk-8u161-linux-x64.tar.gz modules/software/files
    - cp ~/software/fmw_12.2.1.3.0_infrastructure.jar modules/software/files
    - cp ~/software/fmw_12.2.1.3.0_fr_linux64_Disk1_1of2.zip modules/software/files
    - cp ~/software/fmw_12.2.1.3.0_fr_linux64_Disk1_2of2.zip modules/software/files
    - cp ~/software/jce_policy-8.zip modules/software/files
  script:
    - vagrant up ml-fr12213n1
    - vagrant up ml-fr12213n2
  after_script:
    - vagrant destroy ml-fr12213n1 ml-fr12213n2 --force

forms_12214_demo_check:
  extends: .demo_check
  before_script:
    - mkdir -p modules/software/files
    - cp ~/software/jdk-8u231-linux-x64.tar.gz modules/software/files
    - cp ~/software/fmw_12.2.1.4.0_infrastructure.jar modules/software/files
    - cp ~/software/fmw_12.2.1.4.0_fr_linux64_Disk1_1of2.zip modules/software/files
    - cp ~/software/fmw_12.2.1.4.0_fr_linux64_Disk1_2of2.zip modules/software/files
    - cp ~/software/jce_policy-8.zip modules/software/files
  script:
    - vagrant up ml-fr12214n1
    - vagrant up ml-fr12214n2
  after_script:
    - vagrant destroy ml-fr12214n1 ml-fr12214n2 --force
      

soa_12213_demo_check:
  extends: .demo_check
  before_script:
    - mkdir -p modules/software/files
    - cp ~/software/jdk-8u161-linux-x64.tar.gz modules/software/files
    - cp ~/software/fmw_12.2.1.3.0_infrastructure.jar modules/software/files
    - cp ~/software/fmw_12.2.1.3.0_soa.jar.zip modules/software/files
    - cp ~/software/jce_policy-8.zip modules/software/files
  script:
    - vagrant up ml-soa12213n1
    - vagrant up ml-soa12213n2
  after_script:
    - vagrant destroy ml-soa12213n1 ml-soa12213n2  --force

soa_12214_demo_check:
  extends: .demo_check
  before_script:
    - mkdir -p modules/software/files
    - cp ~/software/jdk-8u231-linux-x64.tar.gz modules/software/files
    - cp ~/software/fmw_12.2.1.4.0_infrastructure.jar modules/software/files
    - cp ~/software/fmw_12.2.1.4.0_soa.jar.zip modules/software/files
    - cp ~/software/jce_policy-8.zip modules/software/files
  script:
    - vagrant up ml-soa12214n1
    - vagrant up ml-soa12214n2
  after_script:
    - vagrant destroy ml-soa12214n1 ml-soa12214n2 --force

osb_12213_demo_check:
  extends: .demo_check
  before_script:
    - mkdir -p modules/software/files
    - cp ~/software/jdk-8u161-linux-x64.tar.gz modules/software/files
    - cp ~/software/fmw_12.2.1.3.0_infrastructure.jar modules/software/files
    - cp ~/software/fmw_12.2.1.3.0_osb.jar.zip modules/software/files
    - cp ~/software/jce_policy-8.zip modules/software/files
  script:
    - vagrant up ml-osb12213n1
    - vagrant up ml-osb12213n2
  after_script:
    - vagrant destroy ml-osb12213n1 ml-osb12213n2 --force

osb_12214_demo_check:
  extends: .demo_check
  before_script:
    - mkdir -p modules/software/files
    - cp ~/software/jdk-8u231-linux-x64.tar.gz modules/software/files
    - cp ~/software/fmw_12.2.1.4.0_infrastructure.jar modules/software/files
    - cp ~/software/fmw_12.2.1.4.0_osb.jar.zip modules/software/files
    - cp ~/software/jce_policy-8.zip modules/software/files
  script:
    - vagrant up ml-osb12214n1
    - vagrant up ml-osb12214n2
  after_script:
    - vagrant destroy ml-osb12214n1 ml-osb12214n2 --force

adf_12213_demo_check:
  extends: .demo_check
  before_script:
    - mkdir -p modules/software/files
    - cp ~/software/jdk-8u161-linux-x64.tar.gz modules/software/files
    - cp ~/software/fmw_12.2.1.3.0_infrastructure.jar modules/software/files
    - cp ~/software/jce_policy-8.zip modules/software/files
  script:
    - vagrant up ml-adf12213n1
    - vagrant up ml-adf12213n2
  after_script:
    - vagrant destroy ml-adf12213n1 ml-adf12213n2  --force

adf_12214_demo_check:
  extends: .demo_check
  before_script:
    - mkdir -p modules/software/files
    - cp ~/software/jdk-8u231-linux-x64.tar.gz modules/software/files
    - cp ~/software/fmw_12.2.1.4.0_infrastructure.jar modules/software/files
    - cp ~/software/jce_policy-8.zip modules/software/files
  script:
    - vagrant up ml-adf12214n1
    - vagrant up ml-adf12214n2
  after_script:
    - vagrant destroy ml-adf12214n1 ml-adf12214n2 --force

teardown RCU:
  stage: acceptance teardown
  tags:
    - demo_check
  script:
  - vboxmanage controlvm  ml-rcudb poweroff
  - vboxmanage unregistervm ml-rcudb --delete
  only:
    refs:
      - master
    