---
#
# Include the shared gitlab CI definitions
#
include:
  - project: 'enterprisemodules/gitlab_ci'
    file: 'gitlab-ci.yml'

cache:
  key: "${CI_COMMIT_REF_SLUG}-vagrant"
  paths:
    - .vagrant/
  policy: pull-push
  when: always


setup RCU:
  stage: acceptance setup
  tags:
    - demo_check
  before_script:
    - vagrant destroy -f ml-rcudb || true
    - vagrant destroy -f ml-fmrcudb || true
    - vagrant prepare ml-rcudb
  script:
    - vagrant up ml-rcudb
  only:
    refs:
      - master

# forms_12213_demo_check:
#   extends: .demo_check
#   before_script:
#     - cp ~/software/jdk-8u161-linux-x64.tar.gz modules/software/files
#     - cp ~/software/fmw_12.2.1.3.0_infrastructure.jar modules/software/files
#     - cp ~/software/fmw_12.2.1.3.0_fr_linux64_Disk1_1of2.zip modules/software/files
#     - cp ~/software/fmw_12.2.1.3.0_fr_linux64_Disk1_2of2.zip modules/software/files
#     - cp ~/software/jce_policy-8.zip modules/software/files
#   script:
#     - vagrant up ml-fr12213n1
#     - vagrant up ml-fr12213n2
#   after_script:
#     - vagrant destroy ml-fr12213n1 ml-fr12213n2 --force

forms_12214_demo_check:
  extends: .demo_check
  variables:
    server:  ml-fr12214n1
  before_script:
    - vagrant destroy ml-fr12214n1 ml-fr12214n2 --force || true
    - vagrant prepare ml-fr12214n1
  script:
    - vagrant up ml-fr12214n1
    - vagrant up ml-fr12214n2
  after_script:
    - vagrant destroy ml-fr12214n1 ml-fr12214n2 --force

forms_122119_demo_check:
  extends: .demo_check
  variables:
    server:  ml-fr122119n1
  before_script:
    - vagrant destroy ml-fr122119n1 ml-fr122119n2 --force || true
    - vagrant prepare ml-fr122119n1
  script:
    - vagrant up ml-fr122119n1
    - vagrant up ml-fr122119n2
  after_script:
    - vagrant destroy ml-fr122119n1 ml-fr122119n2 --force

forms_14120_demo_check:
  extends: .demo_check
  variables:
    server:  ml-fr14120n1
  before_script:
    - vagrant destroy ml-fr14120n1 ml-fr14120n2 --force || true
    - vagrant prepare ml-fr14120n1
  script:
    - vagrant up ml-fr14120n1
    - vagrant up ml-fr14120n2
  after_script:
    - vagrant destroy ml-fr14120n1 ml-fr14120n2 --force


# soa_12213_demo_check:
#   extends: .demo_check
#   before_script:
#     - cp ~/software/jdk-8u161-linux-x64.tar.gz modules/software/files
#     - cp ~/software/fmw_12.2.1.3.0_infrastructure.jar modules/software/files
#     - cp ~/software/fmw_12.2.1.3.0_soa.jar.zip modules/software/files
#     - cp ~/software/jce_policy-8.zip modules/software/files
#   script:
#     - vagrant up ml-soa12213n1
#     - vagrant up ml-soa12213n2
#   after_script:
#     - vagrant destroy ml-soa12213n1 ml-soa12213n2  --force

soa_12214_demo_check:
  extends: .demo_check
  variables:
    server:  ml-soa12214n1
  before_script:
    - vagrant destroy ml-soa12214n1 ml-soa12214n2 --force || true
    - vagrant prepare ml-soa12214n1
  script:
    - vagrant up ml-soa12214n1
    - vagrant up ml-soa12214n2
  after_script:
    - vagrant destroy ml-soa12214n1 ml-soa12214n2 --force

soa_14120_demo_check:
  extends: .demo_check
  variables:
    server:  ml-soa14120n1
  before_script:
    - vagrant destroy ml-soa14120n1 ml-soa14120n2 --force || true
    - vagrant prepare ml-soa14120n1
  script:
    - vagrant up ml-soa14120n1
    - vagrant up ml-soa14120n2
  after_script:
    - vagrant destroy ml-soa14120n1 ml-soa14120n2 --force

# osb_12213_demo_check:
#   extends: .demo_check
#   before_script:
#     - cp ~/software/jdk-8u161-linux-x64.tar.gz modules/software/files
#     - cp ~/software/fmw_12.2.1.3.0_infrastructure.jar modules/software/files
#     - cp ~/software/fmw_12.2.1.3.0_osb.jar.zip modules/software/files
#     - cp ~/software/jce_policy-8.zip modules/software/files
#   script:
#     - vagrant up ml-osb12213n1
#     - vagrant up ml-osb12213n2
#   after_script:
#     - vagrant destroy ml-osb12213n1 ml-osb12213n2 --force

osb_12214_demo_check:
  extends: .demo_check
  variables:
    server:  ml-osb12214n1
  before_script:
    - vagrant destroy ml-osb12214n1 ml-osb12214n2 --force || true
    - vagrant prepare ml-osb12214n1
  script:
    - vagrant up ml-osb12214n1
    - vagrant up ml-osb12214n2
  after_script:
    - vagrant destroy ml-osb12214n1 ml-osb12214n2 --force

osb_14120_demo_check:
  extends: .demo_check
  variables:
    server:  ml-osb14120n1
  before_script:
    - vagrant destroy ml-osb14120n1 ml-osb14120n2 --force || true
    - vagrant prepare ml-osb14120n1
  script:
    - vagrant up ml-osb14120n1
    - vagrant up ml-osb14120n2
  after_script:
    - vagrant destroy ml-osb14120n1 ml-osb14120n2 --force

# adf_12213_demo_check:
#   extends: .demo_check
#   before_script:
#     - cp ~/software/jdk-8u161-linux-x64.tar.gz modules/software/files
#     - cp ~/software/fmw_12.2.1.3.0_infrastructure.jar modules/software/files
#     - cp ~/software/jce_policy-8.zip modules/software/files
#   script:
#     - vagrant up ml-adf12213n1
#     - vagrant up ml-adf12213n2
#   after_script:
#     - vagrant destroy ml-adf12213n1 ml-adf12213n2  --force

adf_12214_demo_check:
  extends: .demo_check
  variables:
    server:  ml-adf12214n1
  before_script:
    - vagrant destroy ml-adf12214n1 ml-adf12214n2 --force || true
    - vagrant prepare ml-adf12214n1
  script:
    - vagrant up ml-adf12214n1
    - vagrant up ml-adf12214n2
  after_script:
    - vagrant destroy ml-adf12214n1 ml-adf12214n2 --force

adf_14120_demo_check:
  extends: .demo_check
  variables:
    server:  ml-adf14120n1
  before_script:
    - vagrant destroy ml-adf14120n1 ml-adf14120n2 --force || true
    - vagrant prepare ml-adf14120n1
  script:
    - vagrant up ml-adf14120n1
    - vagrant up ml-adf14120n2
  after_script:
    - vagrant destroy ml-adf14120n1 ml-adf14120n2 --force

teardown RCU:
  stage: acceptance teardown
  tags:
    - demo_check
  script:
    - vagrant destroy ml-rcudb --force
  only:
    refs:
      - master
